SUBJECTS = [
    "Calculus",
    "Linear Algebra",
    "Probability",
    "Statistics",
    "Optimization",
    "Real Analysis",
    "Differential Equations",
    "Numerical Methods",
    "Abstract Algebra",
    "Topology",
    "Machine Learning Mathematics",
]

PROJECT_MODULES = [
    "Gaussian Elimination",
    "LU Decomposition",
    "QR Decomposition",
    "Power Method",
    "Newton Method",
    "Gradient Descent",
    "Monte Carlo",
    "RK4",
    "Euler Method",
]

BOOKS = [
    "Stewart Calculus",
    "Strang Linear Algebra",
    "Book of Proof",
    "Boyce Differential Equations",
]

# Seed rows for the Germany-move tracks. Each entry maps onto the matching
# sheet schema in backend/excel_db.py; statuses use TRACK_STATUS_OPTIONS.
GERMANY_DOCS = [
    ("Passport (valid beyond Oct 2029)", "Identity", ""),
    ("Passport-size photos (biometric)", "Identity", ""),
    ("Birth certificate", "Identity", ""),
    ("10th & 12th marksheets", "Academic", ""),
    ("Bachelor's transcripts (all semesters)", "Academic", ""),
    ("Bachelor's degree certificate", "Academic", ""),
    ("APS certificate (India)", "Academic", "2026-10-31"),
    ("English proficiency certificate (IELTS/TOEFL)", "Language", "2026-11-30"),
    ("German B1 certificate (Goethe/telc)", "Language", "2027-03-31"),
    ("Letters of recommendation", "Academic", "2026-12-15"),
    ("CV (Europass format)", "Academic", "2026-11-30"),
    ("Blocked account confirmation", "Financial", "2027-07-31"),
    ("Travel health insurance", "Visa", "2027-08-15"),
    ("Admission letter", "Visa", ""),
    ("Visa application form + appointment", "Visa", "2027-08-01"),
]

B1_MILESTONES = [
    ("A1.1", "Basics: greetings, numbers, present tense"),
    ("A1.2", "Daily life: routines, food, simple past"),
    ("A2.1", "Conversations: directions, appointments, dative"),
    ("A2.2", "Fluency base: perfekt, modal verbs, letters"),
    ("B1.1", "Opinions: subordinate clauses, genitiv, essays"),
    ("B1.2", "Exam prep: listening, speaking, mock tests"),
]

DEFAULT_MILESTONES = [
    ("Finalize college shortlist (10-12 unis)", "Colleges", "2026-10-15"),
    ("APS certificate obtained", "Documents", "2026-10-31"),
    ("IELTS taken with target score", "Tests", "2026-11-30"),
    ("SOP + LORs finalized", "SOP", "2026-12-15"),
    ("Applications open (Winter 2027)", "Applications", "2026-12-01"),
    ("Submit all applications", "Applications", "2027-07-15"),
    ("German B1 certificate", "Language", "2027-03-31"),
    ("Research internship secured", "Internship", "2027-05-31"),
    ("Blocked account funded", "Finance", "2027-07-31"),
    ("Visa appointment", "Visa", "2027-08-01"),
    ("Visa approved", "Visa", "2027-09-15"),
    ("Fly to Germany", "Move", "2027-09-25"),
]

FINANCE_GOALS = [
    ("Blocked account (1 year)", 11904, "2027-07-31"),
    ("Visa fee", 75, "2027-08-01"),
    ("APS fee", 250, "2026-09-30"),
    ("uni-assist + application fees", 300, "2027-01-31"),
    ("Test fees (IELTS + Goethe B1)", 400, "2026-11-30"),
    ("Flight ticket", 600, "2027-09-01"),
    ("First 2 months buffer", 2000, "2027-09-15"),
]

QUOTES = [
    "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.",
    "Do not worry about your difficulties in mathematics. I can assure you mine are still greater.",
    "What we know is not much. What we do not know is immense.",
    "A theorem is a tool that remembers your work for you.",
]


# German A1 syllabus: (unit, topic, grammar focus, scheduled date).
# Units 1-8 ran Jul 17-20 2026; 9-70 are 2/day from Jul 21 to Aug 20 2026.
# Completion is NOT stored here - it is derived from the Planner OS snapshot,
# since the units are strictly sequential. See backend/german.py.
GERMAN_A1_UNITS: list[tuple[int, str, str, str]] = [
    (1, "Order at a café", "Definite articles (der/die/das) + ich moechte", "2026-07-17"),
    (2, "Introduce yourself and greet others", "sein & personal pronouns (ich bin, du bist)", "2026-07-17"),
    (3, "Introduce your family", "haben + possessives mein/dein", "2026-07-18"),
    (4, "Talk about food", "Indefinite articles (ein/eine) & noun plurals", "2026-07-18"),
    (5, "Ask for directions", "wo? + in/an/auf with dative", "2026-07-19"),
    (6, "Talk about jobs", "Regular verb conjugation, present tense", "2026-07-19"),
    (7, "Use the present tense", "Present tense: irregular verbs & V2 word order", "2026-07-20"),
    (8, "Talk about a party", "Negation: nicht vs kein", "2026-07-20"),
    (9, "Talk about food prices", "Numbers, prices & kosten", "2026-07-21"),
    (10, "Comment on food and drink", "schmecken/gefallen + dative (mir schmeckt...)", "2026-07-21"),
    (11, "Ask questions", "W-questions & yes/no questions (V2 word order)", "2026-07-22"),
    (12, "Discuss family details", "Possessive articles (mein, dein) - nominative", "2026-07-22"),
    (13, "Describe your home", "Two-way prepositions + dative for location (wo?)", "2026-07-23"),
    (14, "Discuss health issues", "Modal verbs koennen/muessen + Mir tut ... weh", "2026-07-23"),
    (15, "Navigate the airport", "Separable verbs (ankommen, abfliegen, einsteigen)", "2026-07-24"),
    (16, "Order food and drink", "Polite requests: moechte + Sie-form", "2026-07-24"),
    (17, "Evaluate items while shopping", "Comparative adjectives (billiger/teurer als)", "2026-07-25"),
    (18, "Navigate school life", "Modal verbs duerfen & sollen", "2026-07-25"),
    (19, "Help with chores", "Accusative case & articles (den/einen)", "2026-07-26"),
    (20, "Plan weekend activities", "Present-for-future + time expressions (am Wochenende)", "2026-07-26"),
    (21, "Use verbs to express preferences", "gern / lieber / am liebsten", "2026-07-27"),
    (22, "Talk about hobbies", "Stem-changing verbs (fahren->faehrt, lesen->liest)", "2026-07-27"),
    (23, "Enjoy a dance party", "Imperative (du-form)", "2026-07-28"),
    (24, "Check in on feelings", "Dative pronouns (mir, dir) + adjectives with sein", "2026-07-28"),
    (25, "Navigate a train station", "Prepositions of movement: nach, zu, mit + dative", "2026-07-29"),
    (26, "Book a hotel room", "Polite Konjunktiv II: haette/wuerde gern", "2026-07-29"),
    (27, "Explore the city", "Two-way prepositions with accusative (wohin?)", "2026-07-30"),
    (28, "Interact and help out at work", "Dative verbs (helfen, danken + dative)", "2026-07-30"),
    (29, "Discuss activities", "Perfekt with haben - regular participles (gemacht)", "2026-07-31"),
    (30, "Collaborate at work", "Perfekt - irregular participles (gesprochen)", "2026-07-31"),
    (31, "Shop for a BBQ", "Quantities: etwas/viel/wenig + accusative", "2026-08-01"),
    (32, "Discuss university life", "Subordinate clause with dass (verb to the end)", "2026-08-01"),
    (33, "Navigate a road trip", "Accusative prepositions (durch, um, fuer, ohne)", "2026-08-02"),
    (34, "Manage daily routines", "Separable + reflexive verbs (aufstehen, sich anziehen)", "2026-08-02"),
    (35, "Indicate ownership", "Possessives all persons (unser/euer/ihr) + Annas Buch", "2026-08-03"),
    (36, "Talk about your neighbors", "Adjective endings after definite article (nominative)", "2026-08-03"),
    (37, "Navigate a city", "Directions & Sie-imperative (gehen Sie, biegen Sie ab)", "2026-08-04"),
    (38, "Discuss the weather", "Impersonal es (es regnet, es ist kalt)", "2026-08-04"),
    (39, "Shop for gifts", "Dative for the recipient (Ich schenke meiner Mutter...)", "2026-08-05"),
    (40, "Talk about your city", "es gibt + accusative; the pronoun man", "2026-08-05"),
    (41, "Go on errands", "muessen + separable verbs; zuerst/dann/danach", "2026-08-06"),
    (42, "Celebrate birthdays", "Ordinal numbers & dates (am dritten Mai)", "2026-08-06"),
    (43, "Borrow books and more", "Dative + accusative together (jemandem etwas geben)", "2026-08-07"),
    (44, "Communicate at work", "Modal verb sollen & reported requests", "2026-08-07"),
    (45, "Send mail and packages", "Dative prepositions with places (zu, nach, aus, bei)", "2026-08-08"),
    (46, "Participate in class", "Subordinate clause with weil (causal)", "2026-08-08"),
    (47, "Shop for clothes", "Adjective endings after indefinite article (accusative)", "2026-08-09"),
    (48, "Participate in a baking competition", "Recipe imperative & sequence connectors", "2026-08-09"),
    (49, "Talk about your siblings", "Comparative with als/wie; describing people", "2026-08-10"),
    (50, "Plan healthy activities", "Reflexive verbs (sich fuehlen, sich bewegen)", "2026-08-10"),
    (51, "Complete a work task", "Perfekt with sein (gegangen, gefahren)", "2026-08-11"),
    (52, "Plan your day", "Time prepositions (am, um, von...bis) + TeKaMoLo", "2026-08-11"),
    (53, "Talk about your childhood", "Praeteritum of sein & haben (war, hatte)", "2026-08-12"),
    (54, "Discuss game nights", "Perfekt practice + connectors (und, dann)", "2026-08-12"),
    (55, "Get ready to have visitors", "Reflexive verbs in the accusative (sich vorbereiten)", "2026-08-13"),
    (56, "Manage health appointments", "muessen/duerfen at the doctor + dative pronouns", "2026-08-13"),
    (57, "Express struggles and emotions", "weil / dass clauses for feelings", "2026-08-14"),
    (58, "Make excuses", "deshalb & deswegen (word order) vs weil", "2026-08-14"),
    (59, "Shop for a party outfit", "Adjective endings review (der/ein + accusative)", "2026-08-15"),
    (60, "Talk about your free time", "Frequency adverbs & word order (oft, manchmal, nie)", "2026-08-15"),
    (61, "Plan a beach trip", "Future with werden + infinitive", "2026-08-16"),
    (62, "Talk about the past", "Perfekt vs Praeteritum - when to use which", "2026-08-16"),
    (63, "Navigate an emergency", "Sie-imperative for emergencies + urgency with muessen", "2026-08-17"),
    (64, "Practice self-care", "Reflexive with dative (sich die Haende waschen)", "2026-08-17"),
    (65, "Discuss clothing donations", "Dative recipients + mehr/weniger", "2026-08-18"),
    (66, "Navigate student life", "Subordinate clause review (weil, dass, wenn)", "2026-08-18"),
    (67, "Describe your home", "wo vs wohin review + adjective endings", "2026-08-19"),
    (68, "Find lost items", "Prepositions of place + Perfekt (habe ... verloren)", "2026-08-19"),
    (69, "Navigate chaotic situations", "Connectors: deshalb, trotzdem + word order", "2026-08-20"),
    (70, "React to a surprise", "A1 wrap-up: modal particles (denn, mal, doch) & review", "2026-08-20"),
]
